import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Horarios from "./horarios";
import ServiciosPrecios from "./servicios_precios";
import GaleriaFotos from "./fotos";
import Resenas from "./resenas";
import Equipo from "./barberos";
import HomePage from "./page";
import Footer from "./footer";
import BeforeAfterSlider from "./before_after";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <HomePage />
        <Horarios />
        <ServiciosPrecios />
        <Equipo />
        <GaleriaFotos />
        <BeforeAfterSlider />
        <Resenas />
        <Footer />
      </body>
    </html>
  );
}
